.catalog:
  name: "Prometheus"
  version: "2.0"
  description: "Prometheus Monitoring Solution with Alert Manager"
  uuid: prometheus-1
  minimum_rancher_version: v0.56.0
  questions:
    - variable: "EMAIL"
      label: "Enter Email Address"
      description: "Specify Email Address to send AlertManger Alerts to your Email"
      default: abhijeet@kamble.com
      required: true
      type: "string"

ranch-eye:
  upgrade_strategy:
    start_first: true

node-exporter:
  upgrade_strategy:
    start_first: true

prometheus:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 9090
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

influxdb:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8086
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

grafana:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 3000
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

rancher-api-integration:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 9010
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

